server:
  port: 9000
spring:
  data:
    mongodb:
      host: 18.197.32.89
      port: 30000
      database: covid19_statistics
kafka:
  bootstrap-address: 3.120.190.247:9092
  group-id: test-consumer-group
  topics:
    aggregated-statistic:
      name: aggregated-statistic
    daily-statistic:
      name: daily-statistic

