server:
  port: 9000
spring:
  data:
    mongodb:
      host: 18.157.141.251
      port: 30000
      database: covid19_statistics
kafka:
  bootstrap-address: localhost:9092
  group-id: statistic
  topics:
    aggregated-statistic:
      name: aggregated-statistic
    daily-statistic:
      name: daily-statistic

