spring.application.name: streams
spring.cloud.stream:
  bindings:
    countries1:
      destination: countries
      consumer:
        applicationId: countries1
    countries2:
      destination: countries
      consumer:
        applicationId: countries2
    aggregated-out-0:
      destination: aggregated-statistic
    daily-out-0:
      destination: daily-statistic
  kafka:
    streams:
      binder:
        brokers: "b-1.awskafkatutorialclu.tfuxdb.c3.kafka.eu-central-1.amazonaws.com:9094,
        b-3.awskafkatutorialclu.tfuxdb.c3.kafka.eu-central-1.amazonaws.com:9094,
        b-2.awskafkatutorialclu.tfuxdb.c3.kafka.eu-central-1.amazonaws.com:9094"+
        applicationId: kafka-stream
        configuration:
          commit.interval.ms: 100
          default:
            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#Enable metrics
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: metrics,health
#Enable logging to debug for spring kafka config
logging:
  level:
    org:
      apache:
        kafka:
          clients:
            consumer:
              internals: DEBUG
    org.springframework.kafka.config: debug