spring.application.name: streams
spring.cloud.stream:
  bindings:
    process-in-0:
      destination: countries
    process-out-0:
      destination: counts
  kafka:
    streams:
      binder:
        applicationId: kafka-stream
        configuration:
          commit.interval.ms: 100
          default:
            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#      bindings:
#        counts:
#          producer:
#            valueSerde: org.springframework.kafka.support.serializer.JsonSerde
#Enable metrics
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: metrics,health
#Enable logging to debug for spring kafka config
logging:
  level:
    org:
      apache:
        kafka:
          clients:
            consumer:
              internals: DEBUG
    org.springframework.kafka.config: debug