logging:
  level:
    web: TRACE
    com:
      covid19:
        statistics:
          api: TRACE
spring:
  rsocket:
    server:
      transport: websocket
      port: 9898
  data:
    mongo:
      repositories:
        type: reactive