logging:
  level:
    web: TRACE
    com:
      covid19:
        statistics:
          api: TRACE
spring:
  rsocket:
    server:
      transport: websocket
      port: 9898
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: abc123
      database: covid19_statistics
      port: 27017
      host: localhost
      repositories:
        type: reactive