logging:
  level:
    web: TRACE
    com:
      covid19:
        statistics:
          api: TRACE
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: covid19_statistics
      port: 30000
      host: localhost
      repositories:
        type: reactive
api:
  rsocket:
    websocket:
      host: localhost
      port: 8080
      mapping-path: /rsocket
      retry: 5
server:
  port: 9090